### PR TITLE
Update test for large objects with a more reasonable hash function.

### PR DESCRIPTION
**Pull request by greg7mdp**
The HashObject uses the following code in the Hash() function:

```
size_t Hash() const {
  g_num_hashes++;
  int hashval = i_;
  for (size_t i = 0; i < Hashsize - sizeof(i_); ++i) {
     hashval += buffer_[i];
  }
  return SPARSEHASH_HASH<int>()(hashval);
}
```

As you can see, when Hashsize is specified as 256, the Hash() function
will iterate and sum 252 bytes.
This is a big contributor to the time spent in sparse, dense and
unordered_map tests, and I feel is unfair when comparing with the
std::map, because the HashObject comparison function compares only the
"i_" member:

```
bool operator==(const class_type& that) const { return this->i_ ==
that.i_; }
bool operator< (const class_type& that) const { return this->i_ <
that.i_; }
bool operator<=(const class_type& that) const { return this->i_ <=
that.i_; }
```

Also, it is not typical for hash functions to take a lot of time to compute everytime the object is inserted or a lookup is performed. If indeed the hash computation is complex and must refer to many members, it should be computed once on demand and stored in the object.

### CODE REVIEW

**Comment by donovanhide** [comment]
Looks good. Apologies for the previous discussion, I hadn't really taken in that the Hash() function was simply adding the bytes and then hashing that value. Seems odd when I look at it now :-)

Thanks again!

**Comment by greg7mdp** [comment]
No problem, I appreciate that you manage this repository carefully and that you are willing to spend a lot of time managing an open source project. Just so you know, I am actually working on a derived version of the sparse hash (sparse only, not dense), very heavily modified, with much better performance, which I'll release in a month or so.

**Comment by greg7mdp** [comment]
Hum, I've made the change in the HTML file, and commited them, but I don't know how to add the commit to the pull request.

**Comment by donovanhide** [comment]
To answer the specific question: If you have created a pull request on a branch of your fork of the code, then any commits and pushes to that specific branch will then automatically show up in the pull request.

**Pull request merged**
