### PR TITLE
Correct the memory usage claims to take into account allocator memory usage

### PR DESCRIPTION
**Pull request by greg7mdp**
The default memory allocator used (libc_allocator_with_realloc)
necessarily has some overhead, as the size of the block is not passed to
free(). The memory usage claims are updated to take into account an
overhead of up to 16 bytes per malloc'ed block.

### CODE REVIEW

**Comment by donovanhide** [comment]
Might be worth actually breaking out your revised calculation to confirm its correctness . My understanding is that a sparsetable consists of sparsegroups with a default of 48 possible entries. If a sparsegroup is fully populated that would be an overhead of 48 bits + sizeof(pointer). The total overhead of a sparsetable is number of sparsegroups*sparsegroup overhead+vector overhead.

Also, you need to make sure that your pull request consists of logical commits rather than your full history of changes :-)

**Comment by greg7mdp** [comment]
Hi Donovan, I'll try breaking it down in a table, please let me know if something is not clear. You did forget the num_buckets in Settings. Also the vector overhead is at the sparsetable level, not the sparsegroup, so it would be negligible (3 pointers) for large maps.

Each sparsegroup has:

|  member                         |        32bit                    |    64 bits                       |
| -----------------| -----------------------| ---------------------------|
|  pointer             | 4 bytes                        |    8 bytes                      |
|  num_buckets   | 2 bytes                         |    2 bytes                     |
|  bitmap             | 6 bytes                         |    6 bytes                     |
| -----------------| -----------------------| ---------------------------|
| total                  | 12 bytes = 96 bits        |   16 bytes = 128 bits   |
| -----------------| -----------------------| ---------------------------|
| because this is the overhead for 48 entries, we divide by 48 |
| -----------------| -----------------------| ---------------------------|
| overhead / entry | 96 / 48 = 2  bit/entry |  128 / 48 = 2.66  bit/entry    |
| -----------------| -----------------------| ---------------------------|
| additional overhead per allocation up to 16 bytes =  128 bits | 
| -----------------| -----------------------| ---------------------------|
| max overhead / entry | (96 + 128) / 48 = 4.66 | (128 + 128) / 48 = 5.33 |

**Comment by donovanhide** [comment]
You were right about the omission of num_buckets per sparsegroup :-) However, I don't believe there will be a heap allocation per sparsegroup entry. For each addition of an entry, the array gets *reallocated* and the entries after the added entry get shifted right:

https://github.com/sparsehash/sparsehash/blob/master/src/sparsehash/sparsetable#L1086-L1092

The reallocation is good, because it means the memory allocator won't delete the previous allocation if there was enough unused space in the previous allocation.

Also, I did mean the vector overhead was at the sparsetable level, I just omitted the brackets, assuming BODMAS :-)

If we can agree on the table, it looks like it should be in the docs as HTML. We should also look at gettings the docs hosted as a Github page, and maybe move it to markdown as a separate pull request.

**Comment by donovanhide** [comment]
Oops, sorry realised you had done the allocation overhead divided by num_buckets. I wrote before drinking coffee :-)

All looks good. Maybe just start another pull request with the table as HTML and the previous text and we're good to merge!

**Comment by donovanhide** [comment]
Hi Greg, responding to your query here, rather than the previous pull request :-)

Sounds like you are getting into a bit of a mess with your github practices. Sometimes, it's just better to fork the project again and put your changes into a single commit, push that to your fork and then click the pull request button. A more advanced way to do it is to create a branch for each set of changes, and do multiple commits to that branch. When ready, select that branch for the pull request.

**Comment by greg7mdp** [comment]
Hum, I've made the change in the HTML file, and commited them, but I don't know how to add the commit to the pull request.

**Comment by donovanhide** [comment]
To answer the specific question: If you have created a pull request on a branch of your fork of the code, then any commits and pushes to that specific branch will then automatically show up in the pull request.

**Comment by greg7mdp** [comment]
Closing this pull request, I have created a new one.

**Pull request closed without merging**
